Update test-and-ship.yml
complete e2e test integration

diff --git a/.github/workflows/test-and-ship.yml b/.github/workflows/test-and-ship.yml
--- a/.github/workflows/test-and-ship.yml
+++ b/.github/workflows/test-and-ship.yml
@@ -8,7 +8,7 @@ env:
   DEFAULT_NODE_VERSION: "16"
 
 jobs:
-  test:
+  cypress-tests-run:
     runs-on: ubuntu-latest
     timeout-minutes: 30
     ## While tests are not fixed
@@ -65,9 +65,103 @@ jobs:
     #   run: |
     #     npm run test;
 
+  e2e-test:
+    needs: []
+    runs-on: ubuntu-latest
+    timeout-minutes: 5
+    continue-on-error: false
+
+    steps:
+      - uses: actions/checkout@v3
+  
+      - uses: actions/checkout@v3
+        with:
+          repository: ushahidi/new-platform-e2e-testing
+          ref: develop
+          path: e2e-testing/
+  
+      ## set up API endpoint
+      - name: Setup API endpoint
+        run: |
+          echo 'BACKEND_URL=https://e2e-laboratory-api.staging.ush.zone' > .env
+  
+      ## same as above step
+      - name: Setup Node
+        uses: actions/setup-node@v3
+        with:
+          node-version: 16
+  
+      - name: Get npm cache directory
+        id: npm-cache-dir
+        run: |
+          echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
+    
+      - uses: actions/cache@v3
+        id: npm-cache
+        with:
+          path: ${{ steps.npm-cache-dir.outputs.dir }}
+          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-node-
+  
+      - name: Install dependencies
+        run: npm install;
+  
+      - name: Run server
+        run: |
+          npm run web:serve &
+  
+      - name: Wait until the front-end is ready
+        run: |
+          retry() {
+            local -r -i max_attempts="$1"; shift
+            local -r cmd="$@"
+            local -i attempt_num=1
+  
+            until $cmd
+            do
+                if (( attempt_num == max_attempts ))
+                then
+                    echo "Attempt $attempt_num failed and there are no more attempts left!"
+                    return 1
+                else
+                    echo "Attempt $attempt_num failed! Trying again in $attempt_num seconds..."
+                    sleep $(( attempt_num++ ))
+                fi
+            done;
+          }
+  
+          server='http://localhost:3000'
+          retry 60 timeout 1 curl --silent ${server}/index.html || { echo "Failed getting index.html!" && exit 1; }
+  
+      - name: Patch cypress config
+        run: |
+          cd e2e-testing
+          echo '{"projectId": "'${CYPRESS_PROJECT_ID}'"}' > cypress.json
+          jq '.baseUrl="http://localhost:3000/"' <<<$(cat cypress.env.json) > cypress.env.json
+  
+      - name: Cypress run
+        uses: cypress-io/github-action@v2
+  
+        with:
+          browser: chrome
+          install-command: npm install
+          record: true
+          parallel: true
+          working-directory: e2e-testing
+  
+        env:
+            CYPRESS_ush_admin_email: "${{secrets.e2e_ush_admin_email}}"
+            CYPRESS_ush_admin_pwd: "${{secrets.e2e_ush_admin_pwd}}"
+            CYPRESS_ush_user_name: "${{secrets.e2e_ush_user_name}}"
+            CYPRESS_ush_user_email: "${{secrets.e2e_ush_user_email}}"
+            CYPRESS_ush_user_pwd: "${{secrets.e2e_ush_user_pwd}}"
+            CYPRESS_RECORD_KEY: ${{ secrets.E2E_CYPRESS_RECORD_KEY }}
+            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
   ship:
-    needs: [test, e2e-test]
-    if: github.event_name == 'push' # not on PRs
+    needs: [ test ]
+    if: github.event_name == 'push'   # not on PRs
     runs-on: ubuntu-latest
     timeout-minutes: 15
 
